site_name: Norawit Nangsue's Blog
site_url: https://5730289021-NN.github.io
theme:
  name: material
  # custom_dir: stylesheets/extra.css
  features:
    - navigation.indexes
  palette:
    scheme: my_color
    # primary: custom
    # accent: DC143C
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  # - search
  - glightbox
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "40%"

extra_javascript:
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

nav:
  # - About Me: 01_about.md
  - Homepage: index.md
  - Portfolio: 02_portfolio.md
  - Present Focus: 03_present_focus.md
  - Contact: 04_contact.md

  # - "#Robofolio":
  #    - Tags: blog/tags.md

markdown_extensions:
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption